function scriptstring=AvizoTrImTemplateUnified(volsize,vname,vnameglob,tname,sname,lnameglob,globallabeldirname,excrop,eycrop,ezcrop,trajlength,CPtraj,voldirname,globalvoldirname,trajdirname,spheredirname,medloc)
%% ORDER OF WORK

% [X] FORMAT EXISTING CODE
% [X] PARAMETERIZE EXISTING CODE (ie: excrop(1) excrop(end), etc)
% [X] DETERMINE UNNECESSARY COMPONENTS
% [X] DETERMINE IF/ELSE MODULES FOR TWO-COLOR, TIME SERIES CREATION, ETC
% [X] REPLACE COLORMAP PATHS
% [X] PARAMETERIZE TR TIME FOR COLORBAR/COLORMAP
% [X] SYNCHRONIZE TRAJ/SPHERE TS PORTS
% [X] CREATE ANIMATION DRAWING OUT TRAJ/SPHERE
% [ ] CREATE ANIMATION TIME LINKED TO STEPPING VOL (NEED IMTIME INPUT!)
% [ ] AUTOMATE CAMERA ZOOM AND ORBIT
% [ ] IS THERE A WAY TO AUTOMATICALLY FIND A "GOOD" DEFAULT CAMERA VIEW?
% [X] ADD DIFFUSIVITY TO CSV
% [X] ADD DIFFUSIVE COLORMAPPED TRAJ
% [ ] ADD 2-COLOR SUPPORT
% [X] ADD GLOBAL TIME MIP VOL
% [X] ADD ORTHO SLICES XY/YZ/XZ NEAR PARTICLE MEDIAN POSITION (WHAT ABOUT
% Z? SHOULD BE NEAR CELL LEVEL? USE SUM INT? POSSIBLY CAN CALCULATE THIS
% USING AVIZO SCRIPTING SO AS NOT TO REQUIRE INPUT/FOREKNOWLEDGE
% [ ] AUTOMATE SNAPSHOT/MOVIE SAVING: TRANSPARENT,
% AXES/SCALEBARS/COLORBARS ON/OFF/VOLUMES ON/OFF. DIFF CAMERA ANGLES.
% [ ] IMPLEMENT MULTI TRAJ CODE - JONATHAN
% [X] ASSIGN PLASMA COLMAP TO GLOBAL VOLUME
% [X] ASSIGN VIRIDIS COLMAP TO CP
% [ ] LEAVE CURRENT TRAJ COLMAP, CHANGE LATER (VIRIDIS WAS CURRENT, CHANGE
% LATER)
% [X] SWITCH COLMAPS/data connects depending on CP/TIME traj
% [X] SWITCH COLBARS 
% [X] LEAVE VID TS UNASSIGNED?
% [X] DISABLE POINT CLOUD BY DEFAULT



% Note: For vertcat to function MUST have line break between lines that end
% with ... and finish with ]; to complete the vertical strcat operation.

%Linebreaks in the text file must be manually defined. It is not clear if
%Avizo interprets these. I think it's PROBABLY just for formatting.

%% DEFINE SPECIAL CHARACTER STRINGS

% strcat(qq,,qq) %Use to encapsulate in quotes
tname=string(tname);
vname=string(vname);
vnameglob=string(vnameglob);

lnameglob=string(lnameglob);
sname=string(sname);
numvol=length(vname);

if numvol>1
    vTS=1;
else
    vTS=0;
end

numtraj=length(tname);
if numtraj>1
    tTS=1;
else
    tTS=0;
end
qq=sprintf('%s',34); % "
% mucode=sprintf('%s',181); %µ = ALT+0181 (!)
linebreak=sprintf('\r'); %return key

% hashtag=sprintf('##') %Not needed
scriptpath="${SCRIPTDIR}/";

%% DEFINE QUOTE STRINGS OF DATA OBJECTS FOR CLEANLINESS

% GENERAL FORM: VARNAME=strcat(qq, ,qq);

%COLORMAPS
PhysicsColmap=strcat(qq,"physics.icol",qq);
VolRenPhysicsColmap=strcat(qq,"physics_VolRend.am",qq);
PlasmaColmap=strcat(qq,"PlasmaBASE.am",qq);
ViridisColmap=strcat(qq,"ViridisBASE.am",qq);
TenStepsColmap=strcat(qq,"tensteps.col",qq);
TenSteps2Colmap=strcat(qq,"tensteps2.col",qq);
StandardColmap=strcat(qq,"standard.icol.am",qq);
Standard2Colmap=strcat(qq,"standard.icol2.am",qq);
Standard3Colmap=strcat(qq,"standard.icol3.am",qq);
Standard4Colmap=strcat(qq,"standard.icol4.am",qq);

%POSSIBLE PATH SCRIPTING: 

%[ load "${SCRIPTDIR}/../Avizo Colormaps/volrenGreenCJ.col.am" ] setLabel
%"volrenGreenCJ.col.am" %THIS FALLS APART IF NOT IN A FOLDER DIRECTLY ABOVE
%THE DATA FOLDER, IF SCRIPT IS IN SUBFOLDER THIS FAILS
%[ load "Z:/courtney/data/Avizo Colormaps/PlasmaBASE.am" ] setLabel "PlasmaBASE.am"

% DISPLAY OBJECTS
TrajSphereObj=strcat(qq,"Traj Sphere",qq); %"Point Cloud View" object class
TrajLineObj=strcat(qq,"Traj Line",qq); %"Line Set View" object class
VolRendSettings=strcat(qq,"Volume Rendering Settings",qq);
VolRendSettings2=strcat(qq,"Volume Rendering Settings2",qq);
SegIso=strcat(qq,"Segmentation Isosurface",qq);
VolRend=strcat(qq,"Volume Rendering",qq);
OrthoSliceXY=strcat(qq,"Ortho Slice XY",qq);
OrthoSliceXZ=strcat(qq,"Ortho Slice XZ",qq);
OrthoSliceYZ=strcat(qq,"Ortho Slice YZ",qq);
% ANNOTATIONS
DmapObj=strcat(qq,"Distance Map",qq);
ScalebarObj=strcat(qq,"Scalebars",qq);
AxesObj=strcat(qq,"Local Axes",qq);
ImColorbarObj=strcat(qq,"Image Colorbar",qq);
TrajColorbarObj=strcat(qq,"Traj Colorbar",qq);




%% DEFINE DATA OBJECTS
for voln=1:numvol
voldatapath(voln)=strcat(qq,scriptpath,voldirname,vname(voln),qq);
voldatapath(voln)=strrep(voldatapath(voln),'\','/');

voldataname(voln)=strcat(qq,vname(voln),qq);
voldataname(voln)=strrep(voldataname(voln),' ','-');

end

for trajn=1:numtraj 
trajdatapath(trajn)=strcat(qq,scriptpath,trajdirname,tname(trajn),qq);
trajdatapath(trajn)=strrep(trajdatapath(trajn),'\','/');

trajdataname(trajn)=strcat(qq,tname(trajn),qq);
trajdataname(trajn)=strrep(trajdataname(trajn),' ','-');

spheredatapath(trajn)=strcat(qq,scriptpath,spheredirname,sname(trajn),qq);
spheredatapath(trajn)=strrep(spheredatapath(trajn),'\','/');

spheredataname(trajn)=strcat(qq,sname(trajn),qq);
spheredataname(trajn)=strrep(spheredataname(trajn),' ','-');
end

globalvoldatapath=strcat(qq,scriptpath,globalvoldirname,vnameglob,qq);
globalvoldatapath=strrep(globalvoldatapath,'\','/');

globalvoldataname=strcat(qq,vnameglob,qq);
globalvoldataname=strrep(vnameglob,' ','-');

globallabeldatapath=strcat(qq,scriptpath,globallabeldirname,lnameglob,qq);
globallabeldatapath=strrep(globallabeldatapath,'\','/');

globallabeldataname=strcat(qq,lnameglob,qq);
globallabeldataname=strrep(lnameglob,' ','-');


ImSeriesControlObj=strcat(qq,"Time Series Control",qq);
TrajSeriesControlObj=strcat(qq,"Time Series Control 2",qq);
SphereSeriesControlObj=strcat(qq,"Time Series Control 3",qq);
SyncPortsObj=strcat(qq,"Synchronize-Ports",qq);
%% DEFINE CONSTANTS

xsize=string(volsize(1));
ysize=string(volsize(2));
zsize=string(volsize(3));
xmin=string(excrop(1));
ymin=string(eycrop(1));
zmin=string(ezcrop(1));
xmax=string(excrop(end));
ymax=string(eycrop(end));
zmax=string(ezcrop(end));
trajlength=string(trajlength);
%% GENERATE SCRIPT TEMPLATE

scriptstring=[ ...
"# Amira Project 201930" ...

linebreak ...

"# Amira Project Template TS TrIm" ...

linebreak ...

"remove -all" ...

"# Create viewers" ...

"viewer setVertical 0" ...

"mainWindow show" ...

"_units setUnitsManagementMode 0" ... 

linebreak ...

"set hideNewModules 1" ...

strcat("[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel " ,PhysicsColmap ) ...

strcat(PhysicsColmap," setNoRemoveAll 1" ) ... 
% 
% strcat(PhysicsColmap," fire") ... 

strcat(PhysicsColmap," setMinMax 0 1") ... 

strcat(PhysicsColmap," flags setValue 1") ... 

strcat(PhysicsColmap," shift setMinMax -1 1") ... 

strcat(PhysicsColmap," shift setButtons 0") ... 

strcat(PhysicsColmap," shift setEditButton 1") ... 

strcat(PhysicsColmap," shift setIncrement 0.133333") ... 

strcat(PhysicsColmap," shift setValue 0") ... 

strcat(PhysicsColmap," shift setSubMinMax -1 1") ... 

strcat(PhysicsColmap," scale setMinMax 0 1") ... 

strcat(PhysicsColmap," scale setButtons 0") ... 

strcat(PhysicsColmap," scale setEditButton 1") ... 

strcat(PhysicsColmap," scale setIncrement 0.1") ... 

strcat(PhysicsColmap," scale setValue 1") ... 

strcat(PhysicsColmap," scale setSubMinMax 0 1") ... 

strcat(PhysicsColmap," fire") ... 

strcat(PhysicsColmap," setViewerMask 16383") ... 

linebreak];

if vTS==1
scriptstring=[scriptstring; ...
        
"set hideNewModules 0"...

strcat("create HxDynamicFileSeriesCtrl ", ImSeriesControlObj) ...

strcat(ImSeriesControlObj," setVar ",qq,"CustomHelp",qq," {HxDynamicFileSeriesCtrl}") ...

strcat(ImSeriesControlObj," init -loadCmd {load ",qq,"$FILENAME",qq,"} \",linebreak)];

for voln=1:numvol
if voln~=numvol
scriptstring=[scriptstring; strcat(voldatapath(voln)," \",linebreak)];
else
scriptstring=[scriptstring; strcat(voldatapath(voln),linebreak)];
end
end
scriptstring=[scriptstring; ...

strcat(ImSeriesControlObj," cachedSteps setMinMax 0 0 ",string(numvol)) ...
    
strcat(ImSeriesControlObj," cachedSteps setValue 0 ",string(numvol)) ...
    
strcat(ImSeriesControlObj," options setValue 0 0") ...
    
strcat(ImSeriesControlObj," options setToggleVisible 0 1") ...
    
strcat(ImSeriesControlObj," options setValue 1 0") ...
    
strcat(ImSeriesControlObj," options setToggleVisible 1 1") ...
    
strcat(ImSeriesControlObj," options setValue 2 0") ...
    
strcat(ImSeriesControlObj," options setToggleVisible 2 1") ...
    
strcat(ImSeriesControlObj," options setValue 3 0") ...
    
strcat(ImSeriesControlObj," options setToggleVisible 3 1") ...
    
strcat(ImSeriesControlObj," fire") ...
    
strcat(ImSeriesControlObj," time setMinMax 0 ",string(numvol-1)) ...
    
strcat(ImSeriesControlObj," time setSubMinMax 0 ",string(numvol-1)) ...
    
strcat(ImSeriesControlObj," time setValue 0") ...
    
strcat(ImSeriesControlObj," time setDiscrete 1") ...
    
strcat(ImSeriesControlObj," time setIncrement 1") ...
    
strcat(ImSeriesControlObj," time animationMode -once") ...
    
strcat(ImSeriesControlObj," time setAnimationDelay 10") ...
    
strcat(ImSeriesControlObj," applyTransformToResult 1") ...
    
strcat(ImSeriesControlObj," fire") ...
    
strcat(ImSeriesControlObj," setViewerMask 16383") ...
    
strcat(ImSeriesControlObj," setPickable 1") ...
];
end
scriptstring=[scriptstring; ...
    
"set hideNewModules 0" ...

strcat("[ load ",globalvoldatapath," ] setLabel ",globalvoldataname) ...

strcat(globalvoldataname," sharedColormap disconnect") ...

strcat(globalvoldataname," sharedColormap setDefaultColor 0.8 0.8 0.8") ...

strcat(globalvoldataname," sharedColormap setDefaultAlpha 0.500000") ...

strcat(globalvoldataname," sharedColormap activateLocalRange 1") ...

strcat(globalvoldataname," sharedColormap setLocalMinMax 0.000000 255.000000") ...

strcat(globalvoldataname," sharedColormap enableAlpha 1") ...

strcat(globalvoldataname," sharedColormap enableAlphaToggle 1") ...

strcat(globalvoldataname," sharedColormap setAutoAdjustRangeMode 1") ...

strcat(globalvoldataname," sharedColormap setColorbarMinMax 0 255") ...

strcat(globalvoldataname," fire") ...

strcat(globalvoldataname," fire") ...

strcat(globalvoldataname," setViewerMask 16383") ...

linebreak];

if ~isempty(lnameglob)
    
scriptstring=[scriptstring; ...
    
"set hideNewModules 0" ...

strcat("[ load ",globallabeldatapath," ] setLabel ",globallabeldataname) ...

strcat(globallabeldataname," setIconPosition 20 119") ...

strcat(globallabeldataname," sharedColormap connect ",qq,"labels.am",qq) ...

strcat(globallabeldataname," sharedColormap setDefaultColor 0.8 0.8 0.8") ...
    
strcat(globallabeldataname," sharedColormap setDefaultAlpha 0.500000") ...
    
strcat(globallabeldataname," sharedColormap activateLocalRange 1") ...
    
strcat(globallabeldataname," sharedColormap setLocalMinMax 1.000000 8.000000") ...
    
strcat(globallabeldataname," sharedColormap enableAlpha 1") ...
    
strcat(globallabeldataname," sharedColormap enableAlphaToggle 1") ...
    
strcat(globallabeldataname," sharedColormap setAutoAdjustRangeMode 1") ...
    
strcat(globallabeldataname," sharedColormap setColorbarMinMax 1 8") ...
    
strcat(globallabeldataname," ImageData connect ",globalvoldataname) ...
    
strcat(globallabeldataname," fire") ...
    
strcat(globallabeldataname," primary setIndex 0 0") ...
    
strcat(globallabeldataname," fire") ...
    
strcat(globallabeldataname," setViewerMask 16383")];

end

scriptstring=[scriptstring; ...
    
"set hideNewModules 0" ...

strcat("[ load ${AMIRA_ROOT}/data/colormaps/physics_VolRend.am ] setLabel ",VolRenPhysicsColmap) ...

strcat(VolRenPhysicsColmap," setVar ",qq,"CustomHelp",qq," {HxColormap256}") ...

strcat(VolRenPhysicsColmap," fire") ...

strcat(VolRenPhysicsColmap," setMinMax 0 1") ...

strcat(VolRenPhysicsColmap," flags setValue 1") ...

strcat(VolRenPhysicsColmap," shift setMinMax -1 1") ...

strcat(VolRenPhysicsColmap," shift setButtons 0") ...

strcat(VolRenPhysicsColmap," shift setEditButton 1") ...

strcat(VolRenPhysicsColmap," shift setIncrement 0.133333") ...

strcat(VolRenPhysicsColmap," shift setValue 0") ...

strcat(VolRenPhysicsColmap," shift setSubMinMax -1 1") ...

strcat(VolRenPhysicsColmap," scale setMinMax 0 1") ...

strcat(VolRenPhysicsColmap," scale setButtons 0") ...

strcat(VolRenPhysicsColmap," scale setEditButton 1") ...

strcat(VolRenPhysicsColmap," scale setIncrement 0.1") ...

strcat(VolRenPhysicsColmap," scale setValue 1") ...

strcat(VolRenPhysicsColmap," scale setSubMinMax 0 1") ...

strcat(VolRenPhysicsColmap," fire") ...

strcat(VolRenPhysicsColmap," setViewerMask 16383") ...

linebreak ...

"set hideNewModules 0" ...

strcat("[ load ",qq,"Z:/courtney/data/Avizo Colormaps/PlasmaBASE.am",qq," ] setLabel ",PlasmaColmap); ...

strcat(PlasmaColmap," setVar ",qq,"CustomHelp",qq," {HxColormap256}") ...

strcat(PlasmaColmap," fire") ...

strcat(PlasmaColmap," setMinMax 0 255") ...

strcat(PlasmaColmap," flags setValue 1") ...

strcat(PlasmaColmap," shift setMinMax -1 1") ...

strcat(PlasmaColmap," shift setButtons 0") ...

strcat(PlasmaColmap," shift setEditButton 1") ...

strcat(PlasmaColmap," shift setIncrement 0.133333") ...

strcat(PlasmaColmap," shift setValue 0") ...

strcat(PlasmaColmap," shift setSubMinMax -1 1") ...

strcat(PlasmaColmap," scale setMinMax 0 1") ...

strcat(PlasmaColmap," scale setButtons 0") ...

strcat(PlasmaColmap," scale setEditButton 1") ...

strcat(PlasmaColmap," scale setIncrement 0.1") ...

strcat(PlasmaColmap," scale setValue 1") ...

strcat(PlasmaColmap," scale setSubMinMax 0 1") ...

strcat(PlasmaColmap," fire") ...

strcat(PlasmaColmap," setViewerMask 16383") ...

linebreak ...

"set hideNewModules 0" ...

strcat("[ load ",qq,"Z:/courtney/data/Avizo Colormaps/ViridisBASE.am",qq," ] setLabel ",ViridisColmap); ...

strcat(ViridisColmap," setVar ",qq,"CustomHelp",qq," {HxColormap256}") ...

strcat(ViridisColmap," fire") ...

strcat(ViridisColmap," setMinMax 5 255") ...

strcat(ViridisColmap," flags setValue 1") ...

strcat(ViridisColmap," shift setMinMax -1 1") ...

strcat(ViridisColmap," shift setButtons 0") ...

strcat(ViridisColmap," shift setEditButton 1") ...

strcat(ViridisColmap," shift setIncrement 0.133333") ...

strcat(ViridisColmap," shift setValue 0") ...

strcat(ViridisColmap," shift setSubMinMax -1 1") ...

strcat(ViridisColmap," scale setMinMax 0 1") ...

strcat(ViridisColmap," scale setButtons 0") ...

strcat(ViridisColmap," scale setEditButton 1") ...

strcat(ViridisColmap," scale setIncrement 0.1") ...

strcat(ViridisColmap," scale setValue 1") ...

strcat(ViridisColmap," scale setSubMinMax 0 1") ...

strcat(ViridisColmap," fire") ...

strcat(ViridisColmap," setViewerMask 16383") ...

linebreak ...

"set hideNewModules 0" ...

strcat("[ load ",qq,"Z:/courtney/data/Avizo Colormaps/tensteps.col",qq," ] setLabel ",TenStepsColmap); ...

% strcat(TenStepsColmap," setIconPosition 495 110") ...
% 
strcat(TenStepsColmap," setVar ",qq,"CustomHelp",qq," {HxColormap256}") ...

strcat(TenStepsColmap," fire") ...

strcat(TenStepsColmap," setMinMax 0.5 255") ...

strcat(TenStepsColmap," flags setValue 1") ...

strcat(TenStepsColmap," shift setMinMax -1 1") ...

strcat(TenStepsColmap," shift setButtons 0") ...

strcat(TenStepsColmap," shift setEditButton 1") ...

strcat(TenStepsColmap," shift setIncrement 0.133333") ...

strcat(TenStepsColmap," shift setValue 0") ...

strcat(TenStepsColmap," shift setSubMinMax -1 1") ...

strcat(TenStepsColmap," scale setMinMax 0 1") ...

strcat(TenStepsColmap," scale setButtons 0") ...

strcat(TenStepsColmap," scale setEditButton 1") ...

strcat(TenStepsColmap," scale setIncrement 0.1") ...

strcat(TenStepsColmap," scale setValue 1") ...

strcat(TenStepsColmap," scale setSubMinMax 0 1") ...

strcat(TenStepsColmap," fire") ...

strcat(TenStepsColmap," setViewerMask 16383") ...

linebreak ...

"set hideNewModules 0" ...

strcat("[ load ",qq,"Z:/courtney/data/Avizo Colormaps/tensteps2.col",qq," ] setLabel ",TenSteps2Colmap) ...
% 
% strcat(TenSteps2Colmap," setIconPosition 1014 378") ...

strcat(TenSteps2Colmap," setVar ",qq,"CustomHelp",qq," {HxColormap256}") ...

strcat(TenSteps2Colmap," fire") ...

strcat(TenSteps2Colmap," setMinMax 0 49") ...

strcat(TenSteps2Colmap," flags setValue 1") ...

strcat(TenSteps2Colmap," shift setMinMax -1 1") ...

strcat(TenSteps2Colmap," shift setButtons 0") ...

strcat(TenSteps2Colmap," shift setEditButton 1") ...

strcat(TenSteps2Colmap," shift setIncrement 0.133333") ...

strcat(TenSteps2Colmap," shift setValue 0") ...

strcat(TenSteps2Colmap," shift setSubMinMax -1 1") ...

strcat(TenSteps2Colmap," scale setMinMax 0 1") ...

strcat(TenSteps2Colmap," scale setButtons 0") ...

strcat(TenSteps2Colmap," scale setEditButton 1") ...

strcat(TenSteps2Colmap," scale setIncrement 0.1") ...

strcat(TenSteps2Colmap," scale setValue 1") ...

strcat(TenSteps2Colmap," scale setSubMinMax 0 1") ...

strcat(TenSteps2Colmap," fire") ...

strcat(TenSteps2Colmap," setViewerMask 16383") ...

linebreak ...

"set hideNewModules 0" ...

strcat("[ load ",qq,"Z:/courtney/data/Avizo Colormaps/standard.icol.am",qq," ] setLabel ",StandardColmap); ...

% strcat(StandardColmap," setIconPosition 759 178") ...
% % 
strcat(StandardColmap," setVar ",qq,"CustomHelp",qq," {HxColormap256}") ...

strcat(StandardColmap," fire") ...

strcat(StandardColmap," setMinMax 0 255") ...

strcat(StandardColmap," flags setValue 1") ...

strcat(StandardColmap," shift setMinMax -1 1") ...

strcat(StandardColmap," shift setButtons 0") ...

strcat(StandardColmap," shift setEditButton 1") ...

strcat(StandardColmap," shift setIncrement 0.133333") ...

strcat(StandardColmap," shift setValue 0") ...

strcat(StandardColmap," shift setSubMinMax -1 1") ...

strcat(StandardColmap," scale setMinMax 0 1") ...

strcat(StandardColmap," scale setButtons 0") ...

strcat(StandardColmap," scale setEditButton 1") ...

strcat(StandardColmap," scale setIncrement 0.1") ...

strcat(StandardColmap," scale setValue 1") ...

strcat(StandardColmap," scale setSubMinMax 0 1") ...

strcat(StandardColmap," fire") ...

strcat(StandardColmap," setViewerMask 16383") ...

linebreak ...

"set hideNewModules 0" ...

strcat("[ load ",qq,"Z:/courtney/data/Avizo Colormaps/standard.icol2.am",qq," ] setLabel ",Standard2Colmap); ...

strcat(Standard2Colmap," setVar ",qq,"CustomHelp",qq," {HxColormap256}") ...

strcat(Standard2Colmap," fire") ...

strcat(Standard2Colmap," setMinMax 0 49") ...

strcat(Standard2Colmap," flags setValue 1") ...

strcat(Standard2Colmap," shift setMinMax -1 1") ...

strcat(Standard2Colmap," shift setButtons 0") ...

strcat(Standard2Colmap," shift setEditButton 1") ...

strcat(Standard2Colmap," shift setIncrement 0.133333") ...

strcat(Standard2Colmap," shift setValue 0") ...

strcat(Standard2Colmap," shift setSubMinMax -1 1") ...

strcat(Standard2Colmap," scale setMinMax 0 1") ...

strcat(Standard2Colmap," scale setButtons 0") ...

strcat(Standard2Colmap," scale setEditButton 1") ...

strcat(Standard2Colmap," scale setIncrement 0.1") ...

strcat(Standard2Colmap," scale setValue 1") ...

strcat(Standard2Colmap," scale setSubMinMax 0 1") ...

strcat(Standard2Colmap," fire") ...

strcat(Standard2Colmap," setViewerMask 16383") ...

linebreak ...
];

if tTS==1
scriptstring=[scriptstring; ...
        
"set hideNewModules 0"...

strcat("create HxDynamicFileSeriesCtrl ", TrajSeriesControlObj) ...

strcat(TrajSeriesControlObj," setVar ",qq,"CustomHelp",qq," {HxDynamicFileSeriesCtrl}") ...

% strcat(TrajSeriesControlObj," init -loadCmd {load -line_set_csv ",qq,"$FILENAME",qq," CSVParams ",qq,"$FILENAME",qq," ",qq,"7 0 1 2 3 -1 -1 -1",qq," ",qq,",",qq," ",qq,"#",qq," 1 0 0 -lineSetParams 0 none 0 1 -dataOnly} \") ... % \ in Avizo code = ... in MATLAB? Means continue cmd on next line
strcat(TrajSeriesControlObj," init -loadCmd {load -line_set_csv ",qq,"$FILENAME",qq," CSVParams ",qq,"$FILENAME",qq," ",qq,"7 0 1 2 3 4 -1 -1",qq," ",qq,",",qq," ",qq,"#",qq," 1 0 0 -lineSetParams 0 none 0 1 -dataOnly} \")]; ... % \ in Avizo code = ... in MATLAB? Means continue cmd on next line;

for trajn=1:numtraj
if trajn~=numtraj

scriptstring=[scriptstring; strcat(trajdatapath(trajn)," \",linebreak)];
else
scriptstring=[scriptstring; strcat(trajdatapath(trajn),linebreak)];
end
end

scriptstring=[scriptstring; ...

strcat(TrajSeriesControlObj," cachedSteps setMinMax 0 0 ",string(numtraj-1)) ...

strcat(TrajSeriesControlObj," cachedSteps setValue 0 ",string(numtraj-1)) ...

strcat(TrajSeriesControlObj," options setValue 0 0") ...

strcat(TrajSeriesControlObj," options setToggleVisible 0 1") ...

strcat(TrajSeriesControlObj," options setValue 1 0") ...

strcat(TrajSeriesControlObj," options setToggleVisible 1 1") ...

strcat(TrajSeriesControlObj," options setValue 2 0") ...

strcat(TrajSeriesControlObj," options setToggleVisible 2 1") ...

strcat(TrajSeriesControlObj," options setValue 3 0") ...

strcat(TrajSeriesControlObj," options setToggleVisible 3 1") ...

strcat(TrajSeriesControlObj," fire") ...

strcat(TrajSeriesControlObj," time setMinMax 0 ",string(numtraj-1)) ...

strcat(TrajSeriesControlObj," time setSubMinMax 0 ",string(numtraj-1)) ...

strcat(TrajSeriesControlObj," time setValue 1") ...

strcat(TrajSeriesControlObj," time setDiscrete 1") ...

strcat(TrajSeriesControlObj," time setIncrement 1") ...

strcat(TrajSeriesControlObj," time animationMode -once") ...

strcat(TrajSeriesControlObj," time setAnimationDelay 10") ...

strcat(TrajSeriesControlObj," applyTransformToResult 1") ...

strcat(TrajSeriesControlObj," fire") ...

strcat(TrajSeriesControlObj," setViewerMask 16383") ...

strcat(TrajSeriesControlObj," setPickable 1",linebreak)];
%
scriptstring=[scriptstring; ...
        
"set hideNewModules 0"...

strcat("create HxDynamicFileSeriesCtrl ", SphereSeriesControlObj) ...

strcat(SphereSeriesControlObj," setVar ",qq,"CustomHelp",qq," {HxDynamicFileSeriesCtrl}") ...

strcat(SphereSeriesControlObj," init -loadCmd {load -point_cloud_csv ",qq,"$FILENAME",qq," CSVParams ",qq,"$FILENAME",qq," ",qq,"7 0 1 2 3 4 -1 -1",qq," ",qq,",",qq," ",qq,"#",qq," 1 0 0 ",qq,"0 0 0 0",qq," -dataOnly} \")]; ... % \ in Avizo code = ... in MATLAB? Means continue cmd on next line;

for trajn=1:numtraj
if trajn~=numtraj

scriptstring=[scriptstring; strcat(spheredatapath(trajn)," \",linebreak)];
else
scriptstring=[scriptstring; strcat(spheredatapath(trajn),linebreak)];
end
end

scriptstring=[scriptstring; ...

strcat(SphereSeriesControlObj," cachedSteps setMinMax 0 0 ",string(numtraj-1)) ...

strcat(SphereSeriesControlObj," cachedSteps setValue 0 ",string(numtraj-1)) ...

strcat(SphereSeriesControlObj," options setValue 0 0") ...

strcat(SphereSeriesControlObj," options setToggleVisible 0 1") ...

strcat(SphereSeriesControlObj," options setValue 1 0") ...

strcat(SphereSeriesControlObj," options setToggleVisible 1 1") ...

strcat(SphereSeriesControlObj," options setValue 2 0") ...

strcat(SphereSeriesControlObj," options setToggleVisible 2 1") ...

strcat(SphereSeriesControlObj," options setValue 3 0") ...

strcat(SphereSeriesControlObj," options setToggleVisible 3 1") ...

strcat(SphereSeriesControlObj," fire") ...

strcat(SphereSeriesControlObj," time setMinMax 0 ",string(numtraj-1)) ...

strcat(SphereSeriesControlObj," time setSubMinMax 0 ",string(numtraj-1)) ...

strcat(SphereSeriesControlObj," time setValue 1") ...

strcat(SphereSeriesControlObj," time setDiscrete 1") ...

strcat(SphereSeriesControlObj," time setIncrement 1") ...

strcat(SphereSeriesControlObj," time animationMode -once") ...

strcat(SphereSeriesControlObj," time setAnimationDelay 10") ...

strcat(SphereSeriesControlObj," applyTransformToResult 1") ...

strcat(SphereSeriesControlObj," fire") ...

strcat(SphereSeriesControlObj," setViewerMask 16383") ...

strcat(SphereSeriesControlObj," setPickable 1",linebreak)];
%
else

scriptstring=[scriptstring; ...
    
"set hideNewModules 0" ...

strcat("[ load -line_set_csv ",trajdatapath," CSVParams ",trajdatapath," ",qq,"7 0 1 2 3 4 -1 -1",qq," ",qq,",",qq," ",qq,"#",qq," 1 0 0 -lineSetParams 0 none 0 1 -dataOnly ] setLabel ",trajdataname) ...
% [ load -line_set_csv "${SCRIPTDIR}/210325 TR0674 BJ_TrIm_eGFPVpr_Polybrene AP AREA 001.csv" CSVParams "${SCRIPTDIR}/210325 TR0674 BJ_TrIm_eGFPVpr_Polybrene AP AREA 001.csv" "8 0 1 2 3 -1 -1 -1 -1" "," "#" 1 0 0 -lineSetParams 0 none 0 1 -dataOnly ] setLabel "210325-TR0674-BJ_TrIm_eGFPVpr_Polybrene-AP-AREA-001.csv"

strcat(trajdataname," fire") ...

strcat(trajdataname," fire") ...

strcat(trajdataname," setViewerMask 16383") ...

linebreak ...

"set hideNewModules 0" ...

strcat("[ load -point_cloud_csv ",spheredatapath," CSVParams ",spheredatapath," ",qq,"7 0 1 2 3 4 -1 -1",qq," ",qq,",",qq," ",qq,"#",qq," 1 0 0 ",qq,"0 0 0 0",qq," -dataOnly ] setLabel ",spheredataname) ...
% [ load -line_set_csv "${SCRIPTDIR}/210325 TR0674 BJ_TrIm_eGFPVpr_Polybrene AP AREA 001.csv" CSVParams "${SCRIPTDIR}/210325 TR0674 BJ_TrIm_eGFPVpr_Polybrene AP AREA 001.csv" "8 0 1 2 3 -1 -1 -1 -1" "," "#" 1 0 0 -lineSetParams 0 none 0 1 -dataOnly ] setLabel "210325-TR0674-BJ_TrIm_eGFPVpr_Polybrene-AP-AREA-001.csv"

strcat(spheredataname," fire") ...

strcat(spheredataname," fire") ...

strcat(spheredataname," setViewerMask 16383") ...

linebreak];

end

scriptstring=[scriptstring; ...

"set hideNewModules 0" ...

strcat("[ load ",qq,"Z:/courtney/data/Avizo Colormaps/standard.icol3.am",qq," ] setLabel ",Standard3Colmap) ...

strcat(Standard3Colmap," fire") ...

strcat(Standard3Colmap," setMinMax 0 ",trajlength) ...

strcat(Standard3Colmap," flags setValue 1") ...

strcat(Standard3Colmap," shift setMinMax -1 1") ...

strcat(Standard3Colmap," shift setButtons 0") ...

strcat(Standard3Colmap," shift setEditButton 1") ...

strcat(Standard3Colmap," shift setIncrement 0.133333") ...

strcat(Standard3Colmap," shift setValue 0") ...

strcat(Standard3Colmap," shift setSubMinMax -1 1") ...

strcat(Standard3Colmap," scale setMinMax 0 1") ...

strcat(Standard3Colmap," scale setButtons 0") ...

strcat(Standard3Colmap," scale setEditButton 1") ...

strcat(Standard3Colmap," scale setIncrement 0.1") ...

strcat(Standard3Colmap," scale setValue 1") ...

strcat(Standard3Colmap," scale setSubMinMax 0 1") ...

strcat(Standard3Colmap," fire") ...

strcat(Standard3Colmap," setViewerMask 16383") ...

linebreak ...

"set hideNewModules 0" ...

strcat("[ load ",qq,"Z:/courtney/data/Avizo Colormaps/standard.icol4.am",qq," ] setLabel ",Standard4Colmap) ...

strcat(Standard4Colmap," fire") ...

strcat(Standard4Colmap," setMinMax 0 255") ...

strcat(Standard4Colmap," flags setValue 1") ...

strcat(Standard4Colmap," shift setMinMax -1 1") ...

strcat(Standard4Colmap," shift setButtons 0") ...

strcat(Standard4Colmap," shift setEditButton 1") ...

strcat(Standard4Colmap," shift setIncrement 0.133333") ...

strcat(Standard4Colmap," shift setValue 0") ...

strcat(Standard4Colmap," shift setSubMinMax -1 1") ...

strcat(Standard4Colmap," scale setMinMax 0 1") ...

strcat(Standard4Colmap," scale setButtons 0") ...

strcat(Standard4Colmap," scale setEditButton 1") ...

strcat(Standard4Colmap," scale setIncrement 0.1") ...

strcat(Standard4Colmap," scale setValue 1") ...

strcat(Standard4Colmap," scale setSubMinMax 0 1") ...

strcat(Standard4Colmap," fire") ...

strcat(Standard4Colmap," setViewerMask 16383") ...

linebreak ...

"set hideNewModules 0" ...

strcat("create HxVolumeRenderingSettings ",VolRendSettings) ...

strcat(VolRendSettings," setViewerMask 0") ...

strcat(VolRendSettings," setVar ",qq,"CustomHelp",qq," {HxVolumeRenderingSettings}") ...

linebreak ...

"set hideNewModules 0" ...

strcat(VolRendSettings," data connect ",globalvoldataname) ...

strcat(VolRendSettings," fire") ...

strcat(VolRendSettings," rendering setValue 1") ...

strcat(VolRendSettings," fire") ...

strcat(VolRendSettings," interpolationAdvanced setValue 2") ...

strcat(VolRendSettings," composition setValue 0") ...

strcat(VolRendSettings," moveLowResolutionScale setMinMax 1 10") ...

strcat(VolRendSettings," moveLowResolutionScale setButtons 1") ...

strcat(VolRendSettings," moveLowResolutionScale setEditButton 1") ...

strcat(VolRendSettings," moveLowResolutionScale setIncrement 1") ...

strcat(VolRendSettings," moveLowResolutionScale setValue 1") ...

strcat(VolRendSettings," moveLowResolutionScale setSubMinMax 1 10") ...

strcat(VolRendSettings," samplingQuality setMinMax 0 2") ...

strcat(VolRendSettings," samplingQuality setButtons 0") ...

strcat(VolRendSettings," samplingQuality setEditButton 1") ...

strcat(VolRendSettings," samplingQuality setIncrement 0.133333") ...

strcat(VolRendSettings," samplingQuality setValue 2") ...

strcat(VolRendSettings," samplingQuality setSubMinMax 0 2") ...

strcat(VolRendSettings," opacityThreshold setMinMax 0 1") ...

strcat(VolRendSettings," opacityThreshold setButtons 0") ...

strcat(VolRendSettings," opacityThreshold setEditButton 1") ...

strcat(VolRendSettings," opacityThreshold setIncrement 0.05") ...

strcat(VolRendSettings," opacityThreshold setValue 0.5") ...

strcat(VolRendSettings," opacityThreshold setSubMinMax 0 1") ...

strcat(VolRendSettings," optimizations setValue 0 0") ...

strcat(VolRendSettings," optimizations setToggleVisible 0 1") ...

strcat(VolRendSettings," optimizations setValue 1 1") ...

strcat(VolRendSettings," optimizations setToggleVisible 1 1") ...

strcat(VolRendSettings," optimizations setValue 2 0") ...

strcat(VolRendSettings," optimizations setToggleVisible 2 1") ...

strcat(VolRendSettings," quality setValue 3") ...

strcat(VolRendSettings," fire") ...

strcat(VolRendSettings," artifactsReduction setValue 0 0") ...

strcat(VolRendSettings," artifactsReduction setToggleVisible 0 1") ...

strcat(VolRendSettings," artifactsReduction setValue 1 1") ...

strcat(VolRendSettings," artifactsReduction setToggleVisible 1 1") ...

strcat(VolRendSettings," lighting setState {item 0 1 item 1 0 }") ...

strcat(VolRendSettings," gradient setState {item 0 1 item 2 9.99999974737875e-05 }") ...

strcat(VolRendSettings," effects setValue 0 0") ...

strcat(VolRendSettings," effects setToggleVisible 0 1") ...

strcat(VolRendSettings," effects setValue 1 0") ...

strcat(VolRendSettings," effects setToggleVisible 1 1") ...

strcat(VolRendSettings," effects setValue 2 0") ...

strcat(VolRendSettings," effects setToggleVisible 2 1") ...

strcat(VolRendSettings," effects setValue 3 1") ...

strcat(VolRendSettings," effects setToggleVisible 3 1") ...

strcat(VolRendSettings," edgeEnhancement setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038") ... %This line is bad ... poss deprecated? Matches the original proj script exactly 

strcat(VolRendSettings," edgeEnhancement setValue 0 9.99999974737875e-005") ...

strcat(VolRendSettings," edge2D setState {item 1 0.100000001490116 item 3 0.100000001490116 item 5 1 }") ...

strcat(VolRendSettings," boundaryOpacity setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038") ... %This line is bad ... poss deprecated? Matches the original proj script exactly 

strcat(VolRendSettings," boundaryOpacity setValue 0 2.5") ...

strcat(VolRendSettings," boundaryOpacity setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038") ... %This line is bad ... poss deprecated? Matches the original proj script exactly 

strcat(VolRendSettings," boundaryOpacity setValue 1 2.5") ...

strcat(VolRendSettings," material setIndex 0 2") ...

strcat(VolRendSettings," lightingStyle setIndex 0 0") ...

strcat(VolRendSettings," toneMapping setIndex 0 0") ...

strcat(VolRendSettings," depthOfField setValue 0") ...

strcat(VolRendSettings," blurFactor setMinMax 0.00999999977648258 1") ...

strcat(VolRendSettings," blurFactor setButtons 0") ...

strcat(VolRendSettings," blurFactor setEditButton 1") ...

strcat(VolRendSettings," blurFactor setIncrement 0.066") ...

strcat(VolRendSettings," blurFactor setValue 0.0292857") ...

strcat(VolRendSettings," blurFactor setSubMinMax 0.00999999977648258 1") ...

strcat(VolRendSettings," specularColor setMinMax 0 1") ...

strcat(VolRendSettings," specularColor setButtons 0") ...

strcat(VolRendSettings," specularColor setEditButton 1") ...

strcat(VolRendSettings," specularColor setIncrement 0.1") ...

strcat(VolRendSettings," specularColor setValue 0.4") ...

strcat(VolRendSettings," specularColor setSubMinMax 0 1") ...

strcat(VolRendSettings," shininess setMinMax 0 1") ...

strcat(VolRendSettings," shininess setButtons 0") ...

strcat(VolRendSettings," shininess setEditButton 1") ...

strcat(VolRendSettings," shininess setIncrement 0.1") ...

strcat(VolRendSettings," shininess setValue 0.4") ...

strcat(VolRendSettings," shininess setSubMinMax 0 1") ...

strcat(VolRendSettings," fire") ...

strcat(VolRendSettings," setViewerMask 16383") ...

strcat(VolRendSettings," setPickable 1") ...

linebreak ...


"set hideNewModules 0" ...

strcat("create HxVolumeRender2 ",VolRend) ...

% strcat(VolRend," setIconPosition 1125 116") ...
% 
strcat(VolRend," setVar ",qq,"CustomHelp",qq," {HxVolumeRender2}") ...

strcat(VolRend," data connect ",globalvoldataname) ...

strcat(VolRend," volumeRenderingSettings connect ",VolRendSettings) ...

strcat(VolRend," fire") ...

strcat(VolRend," colormap connect ",PlasmaColmap) ...

strcat(VolRend," colormap setDefaultColor 1 1 1") ...

strcat(VolRend," colormap setDefaultAlpha 0.500000") ...

strcat(VolRend," colormap activateLocalRange 1") ...

strcat(VolRend," colormap setLocalMinMax 0.000000 255.000000") ...

strcat(VolRend," colormap enableAlpha 1") ...

strcat(VolRend," colormap enableAlphaToggle 1") ...

strcat(VolRend," colormap setAutoAdjustRangeMode 1") ...

strcat(VolRend," colormap setColorbarMinMax 0 255") ...

strcat(VolRend," fire") ...

strcat(VolRend," colormapLookup setValue 2") ...

strcat(VolRend," gamma setMinMax 0.100000001490116 8") ...

strcat(VolRend," gamma setButtons 0") ...

strcat(VolRend," gamma setEditButton 1") ...

strcat(VolRend," gamma setIncrement 0.526667") ...

strcat(VolRend," gamma setValue 3") ...

strcat(VolRend," gamma setSubMinMax 0.100000001490116 8") ...

strcat(VolRend," alphaScale setMinMax 0 1") ...

strcat(VolRend," alphaScale setButtons 0") ...

strcat(VolRend," alphaScale setEditButton 1") ...

strcat(VolRend," alphaScale setIncrement 0.1") ...

strcat(VolRend," alphaScale setValue 1") ...

strcat(VolRend," alphaScale setSubMinMax 0 1") ...

strcat(VolRend," channelSelector setState {2 }") ...

strcat(VolRend," fire") ...

strcat(VolRend," setViewerMask 16383") ...

strcat(VolRend," setPickable 1") ...

linebreak ...

"set hideNewModules 0" ...

strcat("create HxScale ",ScalebarObj) ...
    
% strcat(ScalebarObj," setIconPosition 1097 233") ...
% 
strcat(ScalebarObj," setVar ",qq,"CustomHelp",qq," {HxScale}") ...

strcat(ScalebarObj," data connect ",globalvoldataname) ...

strcat(ScalebarObj," fire") ...

strcat(ScalebarObj," posX setMinMax 0.05 0.9") ...

strcat(ScalebarObj," posX setButtons 1") ...

strcat(ScalebarObj," posX setEditButton 1") ...

strcat(ScalebarObj," posX setIncrement 0.05") ...

strcat(ScalebarObj," posX setValue 0.9") ...

% strcat(ScalebarObj," posX setSubMinMax 0.0500000007450581 0.899999976158142") ...
% 
strcat(ScalebarObj," posY setMinMax 0.0500000007450581 0.899999976158142") ...

strcat(ScalebarObj," posY setButtons 1") ...

strcat(ScalebarObj," posY setEditButton 1") ...

strcat(ScalebarObj," posY setIncrement 0.05") ...

strcat(ScalebarObj," posY setValue 0.05") ...
% 
% strcat(ScalebarObj," posY setSubMinMax 0.0500000007450581 0.899999976158142") ...

strcat(ScalebarObj," sizeX setMinMax 0.0500000007450581 0.899999976158142") ...

strcat(ScalebarObj," sizeX setButtons 1") ...

strcat(ScalebarObj," sizeX setEditButton 1") ...

strcat(ScalebarObj," sizeX setIncrement 0.05") ...

strcat(ScalebarObj," sizeX setValue 0.05") ...

strcat(ScalebarObj," sizeX setSubMinMax 0.0500000007450581 0.899999976158142") ...

strcat(ScalebarObj," sizeY setMinMax 0.0500000007450581 0.899999976158142") ...

strcat(ScalebarObj," sizeY setButtons 1") ...

strcat(ScalebarObj," sizeY setEditButton 1") ...

strcat(ScalebarObj," sizeY setIncrement 0.05") ...

strcat(ScalebarObj," sizeY setValue 0.9") ...

strcat(ScalebarObj," sizeY setSubMinMax 0.0500000007450581 0.899999976158142") ...

strcat(ScalebarObj," frame setValue 0 1") ...

strcat(ScalebarObj," frame setToggleVisible 0 1") ...

strcat(ScalebarObj," frame setValue 1 0") ...

strcat(ScalebarObj," frame setToggleVisible 1 1") ...

strcat(ScalebarObj," frame setValue 2 0") ...

strcat(ScalebarObj," frame setToggleVisible 2 1") ...

strcat(ScalebarObj," reverse setValue 0 0") ...

strcat(ScalebarObj," reverse setToggleVisible 0 1") ...

strcat(ScalebarObj," reverse setValue 1 0") ...

strcat(ScalebarObj," reverse setToggleVisible 1 1") ...

strcat(ScalebarObj," ticks setValue 0 0") ...

strcat(ScalebarObj," ticks setToggleVisible 0 1") ...

strcat(ScalebarObj," ticks setValue 1 0") ...

strcat(ScalebarObj," ticks setToggleVisible 1 1") ...

strcat(ScalebarObj," ticks setValue 2 0") ...

strcat(ScalebarObj," ticks setToggleVisible 2 1") ...

strcat(ScalebarObj," subTicks setValue 0 0") ...

strcat(ScalebarObj," subTicks setToggleVisible 0 1") ...

strcat(ScalebarObj," subTicks setValue 1 0") ...

strcat(ScalebarObj," subTicks setToggleVisible 1 1") ...

strcat(ScalebarObj," axisTitles setValue 0 1") ...

strcat(ScalebarObj," axisTitles setToggleVisible 0 1") ...

strcat(ScalebarObj," axisTitles setValue 1 1") ...

strcat(ScalebarObj," axisTitles setToggleVisible 1 1") ...

strcat(ScalebarObj," axisTitles setValue 2 0") ...

strcat(ScalebarObj," axisTitles setToggleVisible 2 1") ...

strcat(ScalebarObj," unit setState {μm}") ...

strcat(ScalebarObj," color setColor 0 1 1 1") ...

strcat(ScalebarObj," lineWidth setMinMax 1 10") ...

strcat(ScalebarObj," lineWidth setButtons 1") ... %Gives error, matches orig script

strcat(ScalebarObj," lineWidth setEditButton 1") ... %Same

strcat(ScalebarObj," lineWidth setIncrement 1") ... %Same.... why

strcat(ScalebarObj," lineWidth setValue 5") ...

strcat(ScalebarObj," lineWidth setSubMinMax 1 10") ...

strcat(ScalebarObj," font setState {name: ",qq,"Arial",qq," size: 16 buttonText: Select bold: 1 italic: 0 color: 1 1 1}") ...

strcat(ScalebarObj," customSizeOnOff setValue 1") ...

strcat(ScalebarObj," xFactor setMinMax 0 100") ...

strcat(ScalebarObj," xFactor setButtons 0") ...

strcat(ScalebarObj," xFactor setEditButton 1") ...

strcat(ScalebarObj," xFactor setIncrement 6.66667") ...

strcat(ScalebarObj," xFactor setValue 1") ...

strcat(ScalebarObj," xFactor setSubMinMax 0 100") ...

strcat(ScalebarObj," yFactor setMinMax 0 100") ...

strcat(ScalebarObj," yFactor setButtons 0") ...

strcat(ScalebarObj," yFactor setEditButton 1") ...

strcat(ScalebarObj," yFactor setIncrement 6.66667") ...

strcat(ScalebarObj," yFactor setValue 1") ...

strcat(ScalebarObj," yFactor setSubMinMax 0 100") ...

strcat(ScalebarObj," setTextFormat ",qq,"%.4g",qq) ...

strcat(ScalebarObj," fire") ...

strcat(ScalebarObj," setViewerMask 16383") ...

strcat(ScalebarObj," setPickable 1") ...

linebreak ...

"set hideNewModules 0" ...

strcat("create HxAxis ",AxesObj) ...
    
% strcat(AxesObj," setIconPosition 1375 137") ...
% 
strcat(AxesObj," setVar ",qq,"CustomHelp",qq," {HxAxis}") ...

strcat(AxesObj," data connect ",globalvoldataname) ...

strcat(AxesObj," fire") ...

strcat(AxesObj," axis setValue 0 1") ...

strcat(AxesObj," axis setToggleVisible 0 1") ...

strcat(AxesObj," axis setValue 1 1") ...

strcat(AxesObj," axis setToggleVisible 1 1") ...

strcat(AxesObj," axis setValue 2 1") ...

strcat(AxesObj," axis setToggleVisible 2 1") ...

strcat(AxesObj," options setValue 0 1") ...

strcat(AxesObj," options setToggleVisible 0 1") ...

strcat(AxesObj," options setValue 1 0") ...

strcat(AxesObj," options setToggleVisible 1 1") ...

strcat(AxesObj," thickness setMinMax 1 15") ...

strcat(AxesObj," thickness setButtons 0") ...

strcat(AxesObj," thickness setEditButton 1") ...

strcat(AxesObj," thickness setIncrement 0.933333") ...

strcat(AxesObj," thickness setValue 5") ...

strcat(AxesObj," thickness setSubMinMax 1 15") ...

strcat(AxesObj," color setColor 0 1 0 0") ...

strcat(AxesObj," color setColor 1 0 1 0") ...

strcat(AxesObj," color setColor 2 0 0 1") ...

strcat(AxesObj," color setColor 3 1 0.8 0.5") ...

strcat(AxesObj," axisNames setState {text 1 ",qq,"X",qq," text 3 ",qq,"Y",qq," text 5 ",qq,"Z",qq,"}") ...

strcat(AxesObj," textOnOff setValue 0") ...

strcat(AxesObj," font setState {name: ",qq,"Arial",qq," size: 16 buttonText: Select bold: 1 italic: 0 color: 1 1 1}") ...

strcat(AxesObj," fire") ...

strcat(AxesObj," setBoundingBox ",xmin," ",xmax," ",ymin," ",ymax," ",zmin," ",zmax) ...

strcat(AxesObj," setDelta 0 ") ...

strcat(AxesObj," setLocalMode 0 ") ...

strcat(AxesObj," setFlip 0 0 ") ...

strcat(AxesObj," setFlip 1 0 ") ...

strcat(AxesObj," setFlip 2 0 ") ...

strcat(AxesObj," fire") ...

strcat(AxesObj," setViewerMask 16382") ...

strcat(AxesObj," setPickable 1") ...

linebreak ...

"set hideNewModules 0" ...

strcat("create HxDisplayColormap ",ImColorbarObj) ...

strcat(ImColorbarObj," setIconPosition 1149 354") ...

strcat(ImColorbarObj," setVar ",qq,"CustomHelp",qq," {HxDisplayColormap}") ...

strcat(ImColorbarObj," data connect ",VolRend) ...

strcat(ImColorbarObj," fire") ...

strcat(ImColorbarObj," options setState {item 0 1 item 1 0 item 2 1 item 3 1 item 4 1 color 5 0 0 0 item 7 1 }") ...

strcat(ImColorbarObj," fontSettings setState {name: ",qq,"Arial",qq," size: 16 buttonText: Select bold: 1 italic: 0 color: 1 1 1}") ...

strcat(ImColorbarObj," position setMinMax 0 -2000 2000") ...

strcat(ImColorbarObj," position setValue 0 440") ...

strcat(ImColorbarObj," position setMinMax 1 -2000 2000") ...

strcat(ImColorbarObj," position setValue 1 40") ...

strcat(ImColorbarObj," size setMinMax 0 0 1000") ...

strcat(ImColorbarObj," size setValue 0 180") ...

strcat(ImColorbarObj," size setMinMax 1 0 1000") ...

strcat(ImColorbarObj," size setValue 1 18") ...

strcat(ImColorbarObj," labels setState {0/Low 255/High}") ...

strcat(ImColorbarObj," title setState {Image Intensity}") ...

strcat(ImColorbarObj," histogramOptions setState {item 0 1 color 2 0.678431 0.717647 0.792157 color 4 1 1 1 item 6 00 }") ...

strcat(ImColorbarObj," fire") ...

strcat(ImColorbarObj," setViewerMask 16383") ...

strcat(ImColorbarObj," setPickable 1") ...

linebreak ...

"set hideNewModules 0" ...

strcat("create HxDisplayLineSet ",TrajLineObj) ....
    
strcat(TrajLineObj," setIconPosition 87 390") ...

strcat(TrajLineObj," setVar ",qq,"CustomHelp",qq," {HxDisplayLineSet}") ...

strcat(TrajLineObj," setLineWidth 2") ...

strcat(TrajLineObj," setLineColor 1 1 1") ...

strcat(TrajLineObj," setSphereColor 1 1 1") ...

strcat(TrajLineObj," setStripeColorMapping 0") ...

strcat(TrajLineObj," data connect ",trajdataname(1)) ...

strcat(TrajLineObj," colormap connect ",ViridisColmap)];

scriptstring=[scriptstring; ...

strcat(TrajLineObj," colormap setDefaultColor 1 0.8 0.5") ...

strcat(TrajLineObj," colormap setDefaultAlpha 0.500000") ...

strcat(TrajLineObj," colormap activateLocalRange 1") ...

strcat(TrajLineObj," colormap enableAlpha 1") ...

strcat(TrajLineObj," colormap enableAlphaToggle 1") ...

strcat(TrajLineObj," colormap setAutoAdjustRangeMode 1") ...

strcat(TrajLineObj," alphamap disconnect") ...

strcat(TrajLineObj," alphamap setDefaultColor 1 0.8 0.5") ...

strcat(TrajLineObj," alphamap setDefaultAlpha 0.500000") ...

strcat(TrajLineObj," alphamap activateLocalRange 1") ...

strcat(TrajLineObj," alphamap setLocalMinMax 0.000000 1.000000") ...

strcat(TrajLineObj," alphamap enableAlpha 1") ...

strcat(TrajLineObj," alphamap enableAlphaToggle 1") ...

strcat(TrajLineObj," alphamap setAutoAdjustRangeMode 1") ...

strcat(TrajLineObj," alphamap setColorbarMinMax 0 ",trajlength) ...

strcat(TrajLineObj," fire") ...

strcat(TrajLineObj," shape setIndex 0 1") ...

strcat(TrajLineObj," circleComplexity setMinMax 3 30") ...

strcat(TrajLineObj," circleComplexity setButtons 1") ...

strcat(TrajLineObj," circleComplexity setEditButton 1") ...

strcat(TrajLineObj," circleComplexity setIncrement 1") ...

strcat(TrajLineObj," circleComplexity setValue 12") ...

strcat(TrajLineObj," circleComplexity setSubMinMax 3 30") ...

strcat(TrajLineObj," scaleMode setIndex 0 0") ...

strcat(TrajLineObj," scaleFactor setMinMax 0 2.5") ...

strcat(TrajLineObj," scaleFactor setButtons 0") ...

strcat(TrajLineObj," scaleFactor setEditButton 1") ...

strcat(TrajLineObj," scaleFactor setIncrement 0.166667") ...

strcat(TrajLineObj," scaleFactor setValue 1.21359") ...

strcat(TrajLineObj," scaleFactor setSubMinMax 0 2.5") ...

strcat(TrajLineObj," rotateMode setIndex 0 0") ...

strcat(TrajLineObj," rotateMode setIndex 1 2") ...

strcat(TrajLineObj," rotateMode setIndex 2 0") ...

strcat(TrajLineObj," rotateFactor setMinMax 0 360") ...

strcat(TrajLineObj," rotateFactor setButtons 0") ...

strcat(TrajLineObj," rotateFactor setEditButton 1") ...

strcat(TrajLineObj," rotateFactor setIncrement 24") ...

strcat(TrajLineObj," rotateFactor setValue 0") ...

strcat(TrajLineObj," rotateFactor setSubMinMax 0 360") ...

strcat(TrajLineObj," twistMode setIndex 0 0") ...

strcat(TrajLineObj," twistMode setIndex 1 1") ...

strcat(TrajLineObj," twistFactor setMinMax -0.100000001490116 0.100000001490116") ...

strcat(TrajLineObj," twistFactor setButtons 0") ...

strcat(TrajLineObj," twistFactor setEditButton 1") ...

strcat(TrajLineObj," twistFactor setIncrement 0.0133333") ...

strcat(TrajLineObj," twistFactor setValue 0.05") ...

strcat(TrajLineObj," twistFactor setSubMinMax -0.100000001490116 0.100000001490116")];

if CPtraj==0
scriptstring=[scriptstring; ...

strcat(TrajLineObj," colorMode setIndex 0 1") ...

strcat(TrajLineObj," colorMode setIndex 1 0") ...

strcat(TrajLineObj," colorMode setIndex 2 0") ...

strcat(TrajLineObj," colormap setColorbarMinMax 0 ",trajlength) ...

strcat(TrajLineObj," colormap setLocalMinMax 0.000000 ",trajlength)];

else
    
scriptstring=[scriptstring; ...
    
strcat(TrajLineObj," colorMode setIndex 0 2") ...

strcat(TrajLineObj," colorMode setIndex 1 2") ...

strcat(TrajLineObj," colorMode setIndex 2 0") ...

strcat(TrajLineObj," colormap setColorbarMinMax 0 2") ...

strcat(TrajLineObj," colormap setLocalMinMax 0.000000 2")];

end

scriptstring=[scriptstring; ...

strcat(TrajLineObj," spheres setIndex 0 0") ...

strcat(TrajLineObj," sphereScale setMinMax 0 2.5") ...

strcat(TrajLineObj," sphereScale setButtons 0") ...

strcat(TrajLineObj," sphereScale setEditButton 1") ...

strcat(TrajLineObj," sphereScale setIncrement 0.166667") ...

strcat(TrajLineObj," sphereScale setValue 0.266667") ...

strcat(TrajLineObj," sphereScale setSubMinMax 0 2.5") ...

strcat(TrajLineObj," sphereColor setIndex 0 1") ...

strcat(TrajLineObj," sphereColor setIndex 1 0") ...

strcat(TrajLineObj," sphereComplexity setMinMax 0.0560000017285347 1") ...

strcat(TrajLineObj," sphereComplexity setButtons 0") ...

strcat(TrajLineObj," sphereComplexity setEditButton 1") ...

strcat(TrajLineObj," sphereComplexity setIncrement 0.0629333") ...

strcat(TrajLineObj," sphereComplexity setValue 0.2") ...

strcat(TrajLineObj," sphereComplexity setSubMinMax 0.0560000017285347 1") ...

strcat(TrajLineObj," fire") ...

strcat(TrajLineObj," setViewerMask 16383") ...

strcat(TrajLineObj," select") ...

strcat(TrajLineObj," setPickable 1") ...

linebreak ...

"set hideNewModules 0" ...

strcat("create HxDisplayColormap ",TrajColorbarObj) ...
    
strcat(TrajColorbarObj," setIconPosition 309 343") ...

strcat(TrajColorbarObj," setVar ",qq,"CustomHelp",qq," {HxDisplayColormap}") ...

strcat(TrajColorbarObj," data connect ",TrajLineObj) ...

strcat(TrajColorbarObj," fire") ...

strcat(TrajColorbarObj," options setState {item 0 1 item 1 0 item 2 1 item 3 1 item 4 1 color 5 0 0 0 item 7 1 }") ...

strcat(TrajColorbarObj," fontSettings setState {name: ",qq,"Arial",qq," size: 16 buttonText: Select bold: 1 italic: 0 color: 1 1 1}") ...

strcat(TrajColorbarObj," position setMinMax 0 -2000 2000") ...

strcat(TrajColorbarObj," position setValue 0 40") ...

strcat(TrajColorbarObj," position setMinMax 1 -2000 2000") ...

strcat(TrajColorbarObj," position setValue 1 40") ...

strcat(TrajColorbarObj," size setMinMax 0 0 1000") ...

strcat(TrajColorbarObj," size setValue 0 180") ...

strcat(TrajColorbarObj," size setMinMax 1 0 1000") ...

strcat(TrajColorbarObj," size setValue 1 18")];

if CPtraj==0
scriptstring=[scriptstring; ...

strcat(TrajColorbarObj," labels setState {0/0 ",trajlength,"/",trajlength,"}") ... %

strcat(TrajColorbarObj," title setState {Trajectory Time (s)}")];

else
scriptstring=[scriptstring; ...

strcat(TrajColorbarObj," labels setState {0/0 2/2}") ... %

strcat(TrajColorbarObj," title setState {Diffusivity (",sprintf('%s',181,'m',178,'/s)'),"}")];  

end

scriptstring=[scriptstring; ...
    
strcat(TrajColorbarObj," histogramOptions setState {item 0 1 color 2 0.678431 0.717647 0.792157 color 4 1 1 1 item 6 0 }") ...

strcat(TrajColorbarObj," fire") ...

strcat(TrajColorbarObj," setViewerMask 16383") ...

strcat(TrajColorbarObj," setPickable 1") ...

linebreak ...

"set hideNewModules 0" ...

strcat("create HxClusterView ",TrajSphereObj)...

strcat(TrajSphereObj," setIconPosition 1344 141") ...

strcat(TrajSphereObj," setVar ",qq,"CustomHelp",qq," {HxClusterView}") ...

strcat(TrajSphereObj," data connect ",spheredataname(1)) ...

strcat(TrajSphereObj," colormap disconnect") ...

strcat(TrajSphereObj," colormap setDefaultColor 1 0 0") ...

strcat(TrajSphereObj," colormap setDefaultAlpha 0.800000") ...

strcat(TrajSphereObj," colormap activateLocalRange 1") ...

strcat(TrajSphereObj," colormap setLocalMinMax 1.000000 8.000000") ...

strcat(TrajSphereObj," colormap enableAlpha 1") ...

strcat(TrajSphereObj," colormap enableAlphaToggle 1") ...

strcat(TrajSphereObj," colormap setAutoAdjustRangeMode 1") ...

strcat(TrajSphereObj," colormap setColorbarMinMax 0 8") ...

strcat(TrajSphereObj," fire") ...

strcat(TrajSphereObj," color setIndex 0 0") ...

strcat(TrajSphereObj," options setValue 0 1") ...

strcat(TrajSphereObj," options setToggleVisible 0 1") ...

strcat(TrajSphereObj," options setValue 1 1") ...

strcat(TrajSphereObj," options setToggleVisible 1 1") ...

strcat(TrajSphereObj," options setValue 2 0") ...

strcat(TrajSphereObj," options setToggleVisible 2 1") ...

strcat(TrajSphereObj," filter setState {(D>0.166)}") ... setState {(D>0.034)}")

strcat(TrajSphereObj," pointSize setMinMax 0 10") ...

strcat(TrajSphereObj," pointSize setButtons 1") ...

strcat(TrajSphereObj," pointSize setEditButton 1") ...

strcat(TrajSphereObj," pointSize setIncrement 1") ...

strcat(TrajSphereObj," pointSize setValue 10") ...

strcat(TrajSphereObj," pointSize setSubMinMax 0 10") ...

strcat(TrajSphereObj," scaleData setIndex 0 0") ...

strcat(TrajSphereObj," sphereScale setMinMax -1 1") ...

strcat(TrajSphereObj," sphereScale setButtons 0") ...

strcat(TrajSphereObj," sphereScale setEditButton 1") ...

strcat(TrajSphereObj," sphereScale setIncrement 0.133333") ...

strcat(TrajSphereObj," sphereScale setValue 0.012987") ...

strcat(TrajSphereObj," sphereScale setSubMinMax -1 1") ...

strcat(TrajSphereObj," filterOnOff setValue 0") ...

strcat(TrajSphereObj," scalePlateOnOff setValue 0") ...

strcat(TrajSphereObj," setBondWidth 1") ...

strcat(TrajSphereObj," setBondColor 0 0 0.1") ...

strcat(TrajSphereObj," fire") ...

strcat(TrajSphereObj," pointSize setMinMax 0 10") ...

strcat(TrajSphereObj," pointSize setButtons 1") ...

strcat(TrajSphereObj," pointSize setEditButton 1") ...

strcat(TrajSphereObj," pointSize setIncrement 1") ...

strcat(TrajSphereObj," pointSize setValue 10") ...

strcat(TrajSphereObj," pointSize setSubMinMax 0 10") ...

strcat(TrajSphereObj," fire") ...

strcat(TrajSphereObj," setViewerMask 0") ...

strcat(TrajSphereObj," select") ...

strcat(TrajSphereObj," setShadowStyle 3") ...

strcat(TrajSphereObj," setPickable 1") ...

"set hideNewModules 0" ...

strcat("create HxOrthoSlice ",OrthoSliceXY) ...

strcat(OrthoSliceXY," setIconPosition 532 75") ...

strcat(OrthoSliceXY," setVar ",qq,"CustomHelp",qq," {HxOrthoSlice}") ...

strcat(OrthoSliceXY," data connect ",globalvoldataname) ...

strcat(OrthoSliceXY," fire") ...

strcat(OrthoSliceXY," sliceOrientation setValue 0") ...

strcat(OrthoSliceXY," fire") ...

% strcat(OrthoSliceXY," origin  setBoundingBox -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038") ...
% 
strcat(OrthoSliceXY," origin  setImmediateMode 0") ...

strcat(OrthoSliceXY," origin  setOrtho 0") ...

strcat(OrthoSliceXY," origin  showDragger 0") ...

strcat(OrthoSliceXY," origin  showPoints 0") ...

strcat(OrthoSliceXY," origin  setPointScale 1") ...

strcat(OrthoSliceXY," origin  showOptionButton 1") ...

strcat(OrthoSliceXY," origin  setNumPoints 1 1 1") ...

% strcat(OrthoSliceXY," origin  setCoord 0 33.7607 48.2437 14.8036") ...
% 
% strcat(OrthoSliceXY," normal  setBoundingBox -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038") ...
% 
% strcat(OrthoSliceXY," normal  setImmediateMode 0") ...
% 
% strcat(OrthoSliceXY," normal  setOrtho 0") ...
% 
% strcat(OrthoSliceXY," normal  showDragger 0") ...
% 
% strcat(OrthoSliceXY," normal  showPoints 0") ...
% 
% strcat(OrthoSliceXY," normal  setPointScale 1") ...
% 
% strcat(OrthoSliceXY," normal  showOptionButton 1") ...
% 
% strcat(OrthoSliceXY," normal  setNumPoints 1 1 1") ...
% 
% strcat(OrthoSliceXY," normal  setCoord 0 1 0 0") ...
% 
strcat(OrthoSliceXY," options setValue 0 0") ...

strcat(OrthoSliceXY," options setToggleVisible 0 1") ...

strcat(OrthoSliceXY," options setValue 1 0") ...

strcat(OrthoSliceXY," options setToggleVisible 1 1") ...

strcat(OrthoSliceXY," options setValue 2 0") ...

strcat(OrthoSliceXY," options setToggleVisible 2 1") ...

strcat(OrthoSliceXY," mappingType setIndex 0 0") ...

strcat(OrthoSliceXY," contrastLimit setMinMax 0 -16777216 16777216") ...

strcat(OrthoSliceXY," contrastLimit setValue 0 7") ...

strcat(OrthoSliceXY," colormap connect ",PlasmaColmap) ...

strcat(OrthoSliceXY," colormap setDefaultColor 1 0.8 0.5") ...

strcat(OrthoSliceXY," colormap setDefaultAlpha 1.000000") ...

strcat(OrthoSliceXY," colormap activateLocalRange 1") ...

strcat(OrthoSliceXY," colormap setLocalMinMax 0.000000 255.000000") ...

strcat(OrthoSliceXY," colormap enableAlpha 0") ...

strcat(OrthoSliceXY," colormap enableAlphaToggle 1") ...

strcat(OrthoSliceXY," colormap setAutoAdjustRangeMode 1") ...

strcat(OrthoSliceXY," colormap setColorbarMinMax 0 255") ...

% strcat(OrthoSliceXY," sliceNumber setMinMax 0 516") ...
% 
strcat(OrthoSliceXY," sliceNumber setButtons 1") ...

strcat(OrthoSliceXY," sliceNumber setEditButton 1") ...

strcat(OrthoSliceXY," sliceNumber setIncrement 1") ...

strcat(OrthoSliceXY," sliceNumber setValue ",medloc(3)) ...

% strcat(OrthoSliceXY," sliceNumber setSubMinMax 0 516") ...
% 
strcat(OrthoSliceXY," transparency setValue 0") ...

strcat(OrthoSliceXY," alpha setMinMax 0 -16777216 16777216") ...

strcat(OrthoSliceXY," alpha setValue 0 0") ...

strcat(OrthoSliceXY," alpha setMinMax 1 -16777216 16777216") ...

strcat(OrthoSliceXY," alpha setValue 1 255") ...

strcat(OrthoSliceXY," frameSettings setState {item 0 1 item 2 1 color 3 1 0.5 0 }") ...

strcat(OrthoSliceXY," embossingOnOff setValue 0") ...

strcat(OrthoSliceXY," depth setMinMax -60 60") ...

strcat(OrthoSliceXY," depth setButtons 0") ...

strcat(OrthoSliceXY," depth setEditButton 1") ...

strcat(OrthoSliceXY," depth setIncrement 8") ...

strcat(OrthoSliceXY," depth setValue 2") ...

strcat(OrthoSliceXY," depth setSubMinMax -60 60") ...

strcat(OrthoSliceXY," setViewerMask 0") ...

strcat(OrthoSliceXY," setPickable 1") ...

strcat(OrthoSliceXY," fire") ...

"set hideNewModules 0" ...

strcat("create HxOrthoSlice ",OrthoSliceXZ) ...

strcat(OrthoSliceXZ," setIconPosition 532 75") ...

strcat(OrthoSliceXZ," setVar ",qq,"CustomHelp",qq," {HxOrthoSlice}") ...

strcat(OrthoSliceXZ," data connect ",globalvoldataname) ...

strcat(OrthoSliceXZ," fire") ...

strcat(OrthoSliceXZ," sliceOrientation setValue 1") ...

strcat(OrthoSliceXZ," fire") ...
% 
% strcat(OrthoSliceXZ," origin  setBoundingBox -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038") ...
% 
% strcat(OrthoSliceXZ," origin  setImmediateMode 0") ...
% 
% strcat(OrthoSliceXZ," origin  setOrtho 0") ...
% 
% strcat(OrthoSliceXZ," origin  showDragger 0") ...
% 
% strcat(OrthoSliceXZ," origin  showPoints 0") ...
% 
% strcat(OrthoSliceXZ," origin  setPointScale 1") ...
% 
% strcat(OrthoSliceXZ," origin  showOptionButton 1") ...
% 
% strcat(OrthoSliceXZ," origin  setNumPoints 1 1 1") ...
% 
% strcat(OrthoSliceXZ," origin  setCoord 0 33.7607 48.2437 14.8036") ...
% 
% strcat(OrthoSliceXZ," normal  setBoundingBox -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038") ...
% 
% strcat(OrthoSliceXZ," normal  setImmediateMode 0") ...
% 
% strcat(OrthoSliceXZ," normal  setOrtho 0") ...
% 
% strcat(OrthoSliceXZ," normal  showDragger 0") ...
% 
% strcat(OrthoSliceXZ," normal  showPoints 0") ...
% 
% strcat(OrthoSliceXZ," normal  setPointScale 1") ...
% 
% strcat(OrthoSliceXZ," normal  showOptionButton 1") ...
% 
% strcat(OrthoSliceXZ," normal  setNumPoints 1 1 1") ...
% 
% strcat(OrthoSliceXZ," normal  setCoord 0 1 0 0") ...

strcat(OrthoSliceXZ," options setValue 0 0") ...

strcat(OrthoSliceXZ," options setToggleVisible 0 1") ...

strcat(OrthoSliceXZ," options setValue 1 0") ...

strcat(OrthoSliceXZ," options setToggleVisible 1 1") ...

strcat(OrthoSliceXZ," options setValue 2 0") ...

strcat(OrthoSliceXZ," options setToggleVisible 2 1") ...

strcat(OrthoSliceXZ," mappingType setIndex 0 0") ...

strcat(OrthoSliceXZ," contrastLimit setMinMax 0 -16777216 16777216") ...

strcat(OrthoSliceXZ," contrastLimit setValue 0 7") ...

strcat(OrthoSliceXZ," colormap connect ",PlasmaColmap) ...

strcat(OrthoSliceXZ," colormap setDefaultColor 1 0.8 0.5") ...

strcat(OrthoSliceXZ," colormap setDefaultAlpha 1.000000") ...

strcat(OrthoSliceXZ," colormap activateLocalRange 1") ...

strcat(OrthoSliceXZ," colormap setLocalMinMax 0.000000 255.000000") ...

strcat(OrthoSliceXZ," colormap enableAlpha 0") ...

strcat(OrthoSliceXZ," colormap enableAlphaToggle 1") ...

strcat(OrthoSliceXZ," colormap setAutoAdjustRangeMode 1") ...

strcat(OrthoSliceXZ," colormap setColorbarMinMax 0 255") ...

% strcat(OrthoSliceXZ," sliceNumber setMinMax 0 516") ...
% 
strcat(OrthoSliceXZ," sliceNumber setButtons 1") ...

strcat(OrthoSliceXZ," sliceNumber setEditButton 1") ...

strcat(OrthoSliceXZ," sliceNumber setIncrement 1") ...

strcat(OrthoSliceXZ," sliceNumber setValue ",medloc(2)) ...

% strcat(OrthoSliceXZ," sliceNumber setSubMinMax 0 516") ...
% 
strcat(OrthoSliceXZ," transparency setValue 0") ...

strcat(OrthoSliceXZ," alpha setMinMax 0 -16777216 16777216") ...

strcat(OrthoSliceXZ," alpha setValue 0 0") ...

strcat(OrthoSliceXZ," alpha setMinMax 1 -16777216 16777216") ...

strcat(OrthoSliceXZ," alpha setValue 1 255") ...

strcat(OrthoSliceXZ," frameSettings setState {item 0 1 item 2 1 color 3 1 0.5 0 }") ...

strcat(OrthoSliceXZ," embossingOnOff setValue 0") ...

strcat(OrthoSliceXZ," depth setMinMax -60 60") ...

strcat(OrthoSliceXZ," depth setButtons 0") ...

strcat(OrthoSliceXZ," depth setEditButton 1") ...

strcat(OrthoSliceXZ," depth setIncrement 8") ...

strcat(OrthoSliceXZ," depth setValue 2") ...

strcat(OrthoSliceXZ," depth setSubMinMax -60 60") ...

strcat(OrthoSliceXZ," setViewerMask 0") ...

strcat(OrthoSliceXZ," setPickable 1") ...

strcat(OrthoSliceXZ," fire") ...

"set hideNewModules 0" ...

strcat("create HxOrthoSlice ",OrthoSliceYZ) ...

strcat(OrthoSliceYZ," setIconPosition 532 75") ...

strcat(OrthoSliceYZ," setVar ",qq,"CustomHelp",qq," {HxOrthoSlice}") ...

strcat(OrthoSliceYZ," data connect ",globalvoldataname) ...

strcat(OrthoSliceYZ," fire") ...

strcat(OrthoSliceYZ," sliceOrientation setValue 2") ...

strcat(OrthoSliceYZ," fire") ...
% 
% strcat(OrthoSliceYZ," origin  setBoundingBox -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038") ...
% 
% strcat(OrthoSliceYZ," origin  setImmediateMode 0") ...
% 
% strcat(OrthoSliceYZ," origin  setOrtho 0") ...
% 
% strcat(OrthoSliceYZ," origin  showDragger 0") ...
% 
% strcat(OrthoSliceYZ," origin  showPoints 0") ...
% 
% strcat(OrthoSliceYZ," origin  setPointScale 1") ...
% 
% strcat(OrthoSliceYZ," origin  showOptionButton 1") ...
% 
% strcat(OrthoSliceYZ," origin  setNumPoints 1 1 1") ...
% 
% strcat(OrthoSliceYZ," origin  setCoord 0 33.7607 48.2437 14.8036") ...
% 
% strcat(OrthoSliceYZ," normal  setBoundingBox -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038 -3.40282e+038 3.40282e+038") ...
% 
% strcat(OrthoSliceYZ," normal  setImmediateMode 0") ...
% 
% strcat(OrthoSliceYZ," normal  setOrtho 0") ...
% 
% strcat(OrthoSliceYZ," normal  showDragger 0") ...
% 
% strcat(OrthoSliceYZ," normal  showPoints 0") ...
% 
% strcat(OrthoSliceYZ," normal  setPointScale 1") ...
% 
% strcat(OrthoSliceYZ," normal  showOptionButton 1") ...
% 
% strcat(OrthoSliceYZ," normal  setNumPoints 1 1 1") ...
% 
% strcat(OrthoSliceYZ," normal  setCoord 0 1 0 0") ...

strcat(OrthoSliceYZ," options setValue 0 0") ...

strcat(OrthoSliceYZ," options setToggleVisible 0 1") ...

strcat(OrthoSliceYZ," options setValue 1 0") ...

strcat(OrthoSliceYZ," options setToggleVisible 1 1") ...

strcat(OrthoSliceYZ," options setValue 2 0") ...

strcat(OrthoSliceYZ," options setToggleVisible 2 1") ...

strcat(OrthoSliceYZ," mappingType setIndex 0 0") ...

strcat(OrthoSliceYZ," contrastLimit setMinMax 0 -16777216 16777216") ...

strcat(OrthoSliceYZ," contrastLimit setValue 0 7") ...

strcat(OrthoSliceYZ," colormap connect ",PlasmaColmap) ...

strcat(OrthoSliceYZ," colormap setDefaultColor 1 0.8 0.5") ...

strcat(OrthoSliceYZ," colormap setDefaultAlpha 1.000000") ...

strcat(OrthoSliceYZ," colormap activateLocalRange 1") ...

strcat(OrthoSliceYZ," colormap setLocalMinMax 0.000000 255.000000") ...

strcat(OrthoSliceYZ," colormap enableAlpha 0") ...

strcat(OrthoSliceYZ," colormap enableAlphaToggle 1") ...

strcat(OrthoSliceYZ," colormap setAutoAdjustRangeMode 1") ...

strcat(OrthoSliceYZ," colormap setColorbarMinMax 0 255") ...

% strcat(OrthoSliceYZ," sliceNumber setMinMax 0 516") ...
% 
strcat(OrthoSliceYZ," sliceNumber setButtons 1") ...

strcat(OrthoSliceYZ," sliceNumber setEditButton 1") ...

strcat(OrthoSliceYZ," sliceNumber setIncrement 1") ...

strcat(OrthoSliceYZ," sliceNumber setValue ",medloc(1)) ...
% 
% strcat(OrthoSliceYZ," sliceNumber setSubMinMax 0 516") ...

strcat(OrthoSliceYZ," transparency setValue 0") ...

strcat(OrthoSliceYZ," alpha setMinMax 0 -16777216 16777216") ...

strcat(OrthoSliceYZ," alpha setValue 0 0") ...

strcat(OrthoSliceYZ," alpha setMinMax 1 -16777216 16777216") ...

strcat(OrthoSliceYZ," alpha setValue 1 255") ...

strcat(OrthoSliceYZ," frameSettings setState {item 0 1 item 2 1 color 3 1 0.5 0 }") ...

strcat(OrthoSliceYZ," embossingOnOff setValue 0") ...

strcat(OrthoSliceYZ," depth setMinMax -60 60") ...

strcat(OrthoSliceYZ," depth setButtons 0") ...

strcat(OrthoSliceYZ," depth setEditButton 1") ...

strcat(OrthoSliceYZ," depth setIncrement 8") ...

strcat(OrthoSliceYZ," depth setValue 2") ...

strcat(OrthoSliceYZ," depth setSubMinMax -60 60") ...

strcat(OrthoSliceYZ," setViewerMask 0") ...

strcat(OrthoSliceYZ," setPickable 1") ...

strcat(OrthoSliceYZ," fire")];

if ~isempty(lnameglob)
    scriptstring=[scriptstring; ...
        
    "set hideNewModules 0" ...
    
strcat("create HxVolumeRenderingSettings ",VolRendSettings2) ...

strcat(VolRendSettings2," setViewerMask 0") ...

strcat(VolRendSettings2," setIconPosition 490 314") ...

"set hideNewModules 0"

strcat(VolRendSettings2," data connect ",globallabeldataname) ...

strcat(VolRendSettings2," fire") ...

strcat(VolRendSettings2," rendering setValue 1") ...

strcat(VolRendSettings2," fire") ...

strcat(VolRendSettings2," interpolationAdvanced setValue 0") ...

strcat(VolRendSettings2," composition setValue 0") ...

strcat(VolRendSettings2," moveLowResolutionScale setMinMax 1 10") ...

strcat(VolRendSettings2," moveLowResolutionScale setButtons 1") ...

strcat(VolRendSettings2," moveLowResolutionScale setEditButton 1") ...

strcat(VolRendSettings2," moveLowResolutionScale setIncrement 1") ...

strcat(VolRendSettings2," moveLowResolutionScale setValue 2") ...

strcat(VolRendSettings2," moveLowResolutionScale setSubMinMax 1 10") ...

strcat(VolRendSettings2," samplingQuality setMinMax 0 2") ...

strcat(VolRendSettings2," samplingQuality setButtons 0") ...

strcat(VolRendSettings2," samplingQuality setEditButton 1") ...

strcat(VolRendSettings2," samplingQuality setIncrement 0.133333") ...

strcat(VolRendSettings2," samplingQuality setValue 1") ...

strcat(VolRendSettings2," samplingQuality setSubMinMax 0 2") ...

strcat(VolRendSettings2," opacityThreshold setMinMax 0 1") ...

strcat(VolRendSettings2," opacityThreshold setButtons 0") ...

strcat(VolRendSettings2," opacityThreshold setEditButton 1") ...

strcat(VolRendSettings2," opacityThreshold setIncrement 0.05") ...

strcat(VolRendSettings2," opacityThreshold setValue 0") ...

strcat(VolRendSettings2," opacityThreshold setSubMinMax 0 1") ...

strcat(VolRendSettings2," optimizations setValue 0 0") ...

strcat(VolRendSettings2," optimizations setToggleVisible 0 1") ...

strcat(VolRendSettings2," optimizations setValue 1 1") ...

strcat(VolRendSettings2," optimizations setToggleVisible 1 1") ...

strcat(VolRendSettings2," optimizations setValue 2 0") ...

strcat(VolRendSettings2," optimizations setToggleVisible 2 1") ...

strcat(VolRendSettings2," quality setValue 3") ...

strcat(VolRendSettings2," fire") ...

strcat(VolRendSettings2," artifactsReduction setValue 0 0") ...

strcat(VolRendSettings2," artifactsReduction setToggleVisible 0 1") ...

strcat(VolRendSettings2," artifactsReduction setValue 1 0") ...

strcat(VolRendSettings2," artifactsReduction setToggleVisible 1 1") ...

strcat(VolRendSettings2," lighting setState {item 0 1 item 1 0 }") ...

strcat(VolRendSettings2," gradient setState {item 0 1 item 2 9.99999974737875e-05 }") ...

strcat(VolRendSettings2," effects setValue 0 0") ...

strcat(VolRendSettings2," effects setToggleVisible 0 1") ...

strcat(VolRendSettings2," effects setValue 1 0") ...

strcat(VolRendSettings2," effects setToggleVisible 1 1") ...

strcat(VolRendSettings2," effects setValue 2 0") ...

strcat(VolRendSettings2," effects setToggleVisible 2 1") ...

strcat(VolRendSettings2," effects setValue 3 0") ...

strcat(VolRendSettings2," effects setToggleVisible 3 1") ...

strcat(VolRendSettings2," edgeEnhancement setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038") ...

strcat(VolRendSettings2," edgeEnhancement setValue 0 9.99999974737875e-005") ...

strcat(VolRendSettings2," edge2D setState {item 1 0.100000001490116 item 3 0.100000001490116 item 5 1 }") ...

strcat(VolRendSettings2," boundaryOpacity setMinMax 0 -3.40282346638529e+038 3.40282346638529e+038") ...

strcat(VolRendSettings2," boundaryOpacity setValue 0 2.5") ...

strcat(VolRendSettings2," boundaryOpacity setMinMax 1 -3.40282346638529e+038 3.40282346638529e+038") ...

strcat(VolRendSettings2," boundaryOpacity setValue 1 2.5") ...

strcat(VolRendSettings2," material setIndex 0 4") ...

strcat(VolRendSettings2," lightingStyle setIndex 0 1") ...

strcat(VolRendSettings2," toneMapping setIndex 0 0") ...

strcat(VolRendSettings2," depthOfField setValue 0") ...

strcat(VolRendSettings2," blurFactor setMinMax 0.00999999977648258 1") ...

strcat(VolRendSettings2," blurFactor setButtons 0") ...

strcat(VolRendSettings2," blurFactor setEditButton 1") ...

strcat(VolRendSettings2," blurFactor setIncrement 0.066") ...

strcat(VolRendSettings2," blurFactor setValue 0.01") ...

strcat(VolRendSettings2," blurFactor setSubMinMax 0.00999999977648258 1") ...

strcat(VolRendSettings2," specularColor setMinMax 0 1") ...

strcat(VolRendSettings2," specularColor setButtons 0") ...

strcat(VolRendSettings2," specularColor setEditButton 1") ...

strcat(VolRendSettings2," specularColor setIncrement 0.1") ...

strcat(VolRendSettings2," specularColor setValue 0.4") ...

strcat(VolRendSettings2," specularColor setSubMinMax 0 1") ...

strcat(VolRendSettings2," shininess setMinMax 0 1") ...

strcat(VolRendSettings2," shininess setButtons 0") ...

strcat(VolRendSettings2," shininess setEditButton 1") ...

strcat(VolRendSettings2," shininess setIncrement 0.1") ...

strcat(VolRendSettings2," shininess setValue 0.4") ...

strcat(VolRendSettings2," shininess setSubMinMax 0 1") ...

strcat(VolRendSettings2," fire") ...

strcat(VolRendSettings2," setViewerMask 16383") ...

strcat(VolRendSettings2," setPickable 1") ...
    
"set hideNewModules 0" ...

strcat("create HxIsosurfaceRender2 ",SegIso) ...

strcat(SegIso,"  data connect ",globallabeldataname) ...

strcat(SegIso,"  colormap connect ",qq,"labels.am",qq) ...

strcat(SegIso," volumeRenderingSettings connect ",VolRendSettings2) ...

strcat(SegIso," colormap connect ",qq,"labelsBinary.am",qq) ...

strcat(SegIso,"  colormap setDefaultColor 1 0.8 0.4") ...

strcat(SegIso,"  colormap setDefaultAlpha 0.500000") ...

strcat(SegIso,"  colormap activateLocalRange 1") ...

strcat(SegIso,"  colormap setLocalMinMax 0.000000 1.000000") ...

strcat(SegIso,"  colormap enableAlpha 1") ...

strcat(SegIso,"  colormap enableAlphaToggle 1") ...

strcat(SegIso,"  colormap setAutoAdjustRangeMode 1") ...

strcat(SegIso,"  colormap setColorbarMinMax 0 1") ...

strcat(SegIso,"  fire") ...
% 
% strcat(SegIso,"  drawStyle setValue 0") ...
% 
% strcat(SegIso,"  fire") ...

strcat(SegIso,"  threshold setMinMax 0 1") ...

strcat(SegIso,"  threshold setButtons 0") ...

strcat(SegIso,"  threshold setEditButton 1") ...

strcat(SegIso,"  threshold setIncrement 0.1") ...

strcat(SegIso,"  threshold setValue 1") ...

strcat(SegIso,"  threshold setSubMinMax 0 1") ...
% 
% strcat(SegIso,"  setLighting 1") ...
% 
% strcat(SegIso,"  doIt hit") ...

strcat(SegIso,"  fire") ...

strcat(SegIso,"  setViewerMask 0") ...

strcat(SegIso,"  select") ...

strcat(SegIso,"  setShadowStyle 3") ...

strcat(SegIso,"  setPickable 1") ...
% 
% strcat(SegIso,"  doIt snap 0 1") ...
    
strcat(SegIso," alphaScale setMinMax 0 1") ...
    
strcat(SegIso," alphaScale setButtons 0") ...

strcat(SegIso," alphaScale setEditButton 1") ...

strcat(SegIso," alphaScale setIncrement 0.1") ...

strcat(SegIso," alphaScale setValue 0.0779221") ...

strcat(SegIso," alphaScale setSubMinMax 0 1") ...

strcat(SegIso," channelSelector setValue 0 1") ...

strcat(SegIso," channelSelector setToggleVisible 0 1") ...

"set hideNewModules 0" ...

strcat("create HxComputeDistanceMap ",DmapObj) ...

strcat(DmapObj,"  setIconPosition 750 304") ...

strcat(DmapObj," data connect ",globallabeldataname) ...

strcat(DmapObj," fire") ...
    
strcat(DmapObj," type setValue 0") ...

strcat(DmapObj," chamferMetric setValue 1") ...

strcat(DmapObj," region setIndex 0 3") ...

strcat(DmapObj," seed  setBoundingBox -30.3582 154.368 124.51 -43.1296 6.9944 24.9944") ...

strcat(DmapObj," seed  setImmediateMode 0") ...

strcat(DmapObj," seed  setOrtho 0") ...

strcat(DmapObj," seed  showDragger 0") ...

strcat(DmapObj," seed  showPoints 0") ...

strcat(DmapObj," seed  setPointScale 1") ...

strcat(DmapObj," seed  showOptionButton 1") ...

strcat(DmapObj," seed  setNumPoints 1 -1 -1") ...

strcat(DmapObj," seed  setCoord 0 0 -43.1296 6.9944") ...

strcat(DmapObj," applyTransformToResult 1") ...

strcat(DmapObj," fire") ...

strcat(DmapObj," setViewerMask 16383") ...

strcat(DmapObj," setPickable 1") ...

strcat(DmapObj," create")];

end

scriptstring=[scriptstring; ...
    
"set hideNewModules 0" ...

linebreak ...

"viewer 0 setCameraOrientation 0.897286 -0.126175 -0.423035 0.920887" ...

"viewer 0 setCameraPosition -14.5927 -101.967 125.686" ... %4.96094 -47.8166 72.9028

"viewer 0 setCameraFocalDistance 177.319" ... 99.2122

"viewer 0 setCameraNearDistance 90.0727" ...

"viewer 0 setCameraFarDistance 270.252" ...

"viewer 0 setCameraType perspective" ...

"viewer 0 setCameraHeightAngle 44.9023" ...

"viewer 0 setAutoRedraw 1" ...

"viewer 0 redraw" ...

linebreak ...

"set hideNewModules 0"];

if tTS==1
scriptstring=[scriptstring; ...
        
strcat(TrajSeriesControlObj," info interconnect ",SphereSeriesControlObj," info") ...

strcat(TrajSeriesControlObj," cachedSteps interconnect ",SphereSeriesControlObj," cachedSteps") ...

strcat(TrajSeriesControlObj," options interconnect ",SphereSeriesControlObj," options") ...

strcat(TrajSeriesControlObj," time interconnect ",SphereSeriesControlObj," time") ...

"set hideNewModules 0" ...
    
strcat("create ",qq,"Synchronize Ports",qq," ",qq,"Synchronize-Ports",qq) ...

strcat(SyncPortsObj," setIconPosition 591 291") ...

strcat(SyncPortsObj," setVar ",qq,"CustomHelp",qq," {SynchronizePorts.html}") ...

strcat(SyncPortsObj," fire") ...

strcat(SyncPortsObj," data connect ",SphereSeriesControlObj) ...

strcat(SyncPortsObj," InputA connect ",TrajSeriesControlObj) ...

strcat(SyncPortsObj," InputB connect ",SphereSeriesControlObj) ...

strcat(SyncPortsObj," applyTransformToResult 1") ...

strcat(SyncPortsObj," fire") ...

strcat(SyncPortsObj," setViewerMask 16383") ...

strcat(SyncPortsObj," setPickable 1") ...

"##### Animations: begin #####" ...

"_animations removeAll" ...

"_animations create {" ...

"<!DOCTYPE NewAnimation>" ...

strcat("<Settings timeUpdateInterval=",qq,"40",qq," playSpeedFactor=",qq,"1",qq," endTime=",qq,string(str2double(trajlength)*1000),qq," currentTime=",qq,"0",qq," currentPlayMode=",qq,"PLAY_MODE_ONCE",qq," endTime=",qq,"60000",qq," createdFromDemoMaker=",qq,"false",qq," startTime=",qq,"0",qq,">") ...

strcat("<Options skipSnapshotEvents=",qq,"false",qq,"snapshotsOutputDirectory=",qq,"${SCRIPTDIR}",qq," skipBreakEvents=",qq,"false",qq," snappingResolution=",qq,"1000",qq," skipGoToEvents=",qq,"false",qq," autoStartActivated=",qq,"false",qq," functionKeysActivated=",qq,"true",qq," skipPauseEvents=",qq,"false",qq,"/>") ...
        
strcat("<AnimationGroup name=",qq,"All",qq,">") ...
        
 strcat("<AnimationGroup name=",TrajSeriesControlObj,">") ...
        
   strcat("<Animation name=",qq,"Time: value",qq,">") ...
        
    strcat("<Keyframe time=",qq,"0",qq," timeLocked=",qq,"false",qq," time=",qq,"0",qq," considerOnlyOneValue=",qq,"true",qq," rightValue=",qq,"0",qq," leftValue=",qq,"0",qq," interpolationCurve=",qq,"0",qq,"/>") ...
    
    strcat("<Keyframe time=",qq,string(str2double(trajlength)*1000),qq," timeLocked=",qq,"false",qq," time=",qq,string(str2double(trajlength)*1000),qq," considerOnlyOneValue=",qq,"true",qq," rightValue=",qq,string(numtraj-1),qq," leftValue=",qq,string(numtraj-1),qq," interpolationCurve=",qq,"0",qq,"/>") ...    
        
   "</Animation>" ...

  "</AnimationGroup>" ...

 "</AnimationGroup>" ...

"</Settings>" ...

"}" ...

"_animations setCurrentAnimationDirector {NewAnimation}" ...

"##### Animations: end #####"];
end

scriptstring=[scriptstring; ...
    
"correlationPanel closeTabs" ...
    
strcat("correlationPanel setTabName 0 ",qq,"Correlation 1",qq) ...
    
"correlationPanel 0 setLogScalingOnAxis 0 0" ...
    
"correlationPanel 0 setLogScalingOnAxis 1 0" ...

linebreak ...

"histogramPanel closeTabs" ...
    
strcat("histogramPanel setTabName 0 ",qq,"Histogram 1",qq) ...
    
"histogramPanel 0 setLogScalingOnAxis 0 0" ...
    
"histogramPanel 0 setLogScalingOnAxis 1 1" ...

linebreak ...

"theObjectPool setSelectionOrder {Line Set View}" ...

strcat("echo ",qq,"TrIm Project Script Loading Complete",qq) ... % Echo like "disp() in MATLAB
];
end

%CHANGELOG 062521:
%ADDED LABEL VOLUME
%REMOVED VOLREN DEPTH OF FIELD BLUR EFFECT